name: Python application

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Copying configurations
      run: |
        cp contrib/env-sample .env
    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv sync --dev
    - name: Link with flake8
      run: |
        pipenv run flake8 .
    - name: Test with pytest
      run: |
        pipenv run pytest GuaiAcu --cov=GuaiAcu
    - name: Posting Coverage
      env:
        CODECOV_TOKEN: "98f15345-4725-46ec-b7ff-d18a226fdfac"
      run: |
        pipenv run codecov
